module.exports = {
    'up': 'up',
    'down': 'down',
    'remove': 'shift',
    'grid': 'g',
    '0': '0',
    '1': '1',
    '2': '2',
    '3': '3',
    '4': '4',
    '5': '5',
    '6': '6',
    '7': '7',
    '8': '8',
    '9': '9',
    '0': '0',
    '.': '.',
    '-': '-',
    'enter': 'enter',
    'block': 'b',
    'undo': ['ctrl+z', 'command+z'],
    'redo': ['ctrl+shift+z', 'command+shift+z'],
    'save': ['ctrl+s', 'command+s']
}